test PolyInitialized
eisop/jdk pull request #39
Opened 2023-05-26 20:28 UTC by Ao-senXiong

2023-06-05 09:15 UTC, wmdietl commented
I've realized that this repository contains a copy of `checker-qual.jar`. So when we add and use a new qualifier, we need to update that file. I did that in https://github.com/eisop/jdk/pull/39/commits/2f2fcd89f41f798b03b3e16a32d16172e184454a .

2023-06-05 19:56 UTC, wmdietl commented
> @wmdietl It looks like there are still the same failed checks. Could you tell me how to update check-qual.jar file? I will take a look and try to fix it.

When I look at `checker-qual.jar` from https://github.com/eisop/jdk/commit/2f2fcd89f41f798b03b3e16a32d16172e184454a I correctly see the `PolyInitialized.class` file, so I don't think this is the issue.

You can simply do `./gradlew assemble` in the corresponding CF branch and then copy the `checker-qual.jar` file over. That's what I did above, so something else must still be amiss.

2023-06-09 03:08 UTC, Ao-senXiong commented
I think the qualifier could be found after I add the polyinitialized in java/base folder. However, we need a jdk17u fork in eisop org to fix this problem now.

2023-06-11 21:15 UTC, wmdietl approved these changes
#42 removed the extra .jar file and now all tests pass.
This can be merged once the main PR is ready.

2023-06-11 23:38 UTC, Ao-senXiong commented
Thanks!

2023-09-30 17:11 UTC, wmdietl requested changes
Looks good, just the javadoc for PolyInitialized needs to be updated here to be in sync.

2023-09-30 17:11 UTC, wmdietl commented on src/java.base/share/classes/org/checkerframework/checker/initialization/qual/PolyInitialized.java
> + * <p>Any method written using {@link PolyInitialized} conceptually has three versions: one in which
@Ao-senXiong Please sync this file with the original in ECF.

2023-09-30 19:56 UTC, wmdietl approved these changes
I copied over the file.

2023-09-30 19:57 UTC, merged

2023-09-30 19:58 UTC, Ao-senXiong commented
> I copied over the file.

Thanks!